site_name: Connected Widgets
site_url: https://sunkink29.github.io/ConnectedStreamElements/

repo_name: sunkink29/ConnectedStreamElements
repo_url: https://github.com/sunkink29/ConnectedStreamElements
edit_uri: ""

theme:
  name: material

  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: "index.md"
  - Widgets:
      - Spinner: "widgets/spinner.md"
      - Timer: "widgets/timer.md"
      - Chaos Listener: "widgets/chaosContributionListener.md"
